apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: {{ .Values.gateway.servicePort }}
      targetPort: {{ .Values.gateway.port }}
  type: NodePort