gateway:
  image:
    repository: awsfox92/k-api-gateway
    tag: latest
  port: 8000
  servicePort: 8001
  env:
    USERS_SERVICE_URL: http://users:8000
    ORDERS_SERVICE_URL: http://orders:8000

users:
  image:
    repository: awsfox92/k-users
    tag: latest
  port: 8000

orders:
  image:
    repository: awsfox92/k-orders
    tag: latest
  port: 8000