apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: awsfox92/k-users:latest
          command: ["sh", "-c", "uvicorn main:app --reload --host 0.0.0.0"]
          ports:
            - containerPort: 8000
